services:
  postgres:
    image: postgres:16-alpine
    container_name: academy-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: academy
      POSTGRES_PASSWORD: academy
      POSTGRES_DB: academy
    ports:
      - '5433:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
