-- CreateEnum
CREATE TYPE "AdminRole" AS ENUM ('CONTENT_MANAGER', 'RESERVATION_MANAGER', 'ASSESSMENT_MANAGER', 'SUPER_ADMIN');

-- AlterTable
ALTER TABLE "Admin" ADD COLUMN "role" "AdminRole" NOT NULL DEFAULT 'SUPER_ADMIN';
